/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function startGlobalKeyboardHook(cb: ((err: Error | null, arg: string) => any)): void

export declare function startGlobalMouseHook(cb: ((err: Error | null, arg: string) => any)): void

export declare function stopGlobalKeyboardHook(): void

export declare function stopGlobalMouseHook(): void
